<!doctype html>
<html lang="es-ES">
<head>
    <title>Syllabler</title>
    <meta charset="utf8">
    <script href="js/jslogic.js" async></script>
    <link href="styles/style.css" type="text/css" rel="stylesheet">
</head>
<body>
<noscript>
    <div class="noscript">
        <p>With a navigator that supports javascript you will have a better user experience.</p>
        <p>Consider update your browser or machine if it is not compatible with latests browsers... 21st Century...</p>
    </div>
</noscript>
<header>
    <h1>Syllabler (beta)</h1>
</header>

<section>
    <form action="/" method="get" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" id="sylForm">
        <input type="text" id="word" name="word" value="<?php echo utf8_encode($word);?>">
        <input type="hidden" name="json" value="0">
        <button name="submit" value="submit" type="submit" id="sylButton">Silabizar</button>
    </form>
    <p>Errores Conocidos:</p>
    <p>El soporte para palabras con guiones, que debe ser añadido externamente a la clase no está añadido.</p>
    <p>Los prefijos pueden dar lugar a errores por el momento.</p>
    <p>Aunque el algoritmo si lo soporta no está implementado el soporte para "tl" u otras configuraciones. Solo funciona en modalidad Castellano (Español de España y con los errores mencionados en la parte superior.</p>
</section>

<div id="divresult"></div>
<pre id="preresult"><?php if($result) { var_export($result); } ?></pre>

<footer>
    <summary>Por <a href="http://gabi.com.es">Gabriel Trabanco Llano</a> (Contactar via red sociales | Contact through social networks)
        <details><a href="http://twitter.com/gabrieltrabanco">Twitter</a> | <a href="https://es.linkedin.com/in/gabrieltrabanco">LinkeDin</a></details>
    </summary>
    <a href="https://github.com/gtrabanco/Syllabler" title="Project in GitHub" target="_blank">
        <figure>
            <img src="imgs/github.png" alt="GitHub Logo">
            <figcaption>Fork in GitHub</figcaption>
        </figure>
    </a>
</footer>

</body>
</html>